name: CI - Pytest Develop

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  build:

    # Jobs definition
    runs-on: ${{ matrix.os }}
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
    name: pytest (Python ${{ matrix.python-version }}) (OS ${{ matrix.os }})

    # Configure tests
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    - name: Create credentials file
      env:
        MASTR_TOKEN: ${{ secrets.MASTR_TOKEN }}
        MASTR_USER: ${{ secrets.MASTR_USER }}
      run: |
        python -c "from tests import preparation; preparation.create_credentials_file()"
    - name: Test with pytest
      run: |
        pytest -vv
